import { relative } from "node:path";
import type { VerificationRun } from "../core/model.js";

const STATE_LABEL = {
  verified: "Verified",
  failed: "Failed",
  partial: "Partial",
} as const;

function cell(value: string): string {
  return value.replace(/\|/g, "\\|");
}

export function renderMarkdown(run: VerificationRun): string {
  const root = run.project.root;
  const lines: string[] = [];
  lines.push("# VerisKit Verification Report");
  if (run.scope?.kind) {
    lines.push("");
    lines.push(
      `> **Scope:** ${run.scope.kind} — ${run.scope.changedCount} changed file(s). Only affected checks ran; this is not a full verification.`,
    );
  }
  lines.push("");
  lines.push(`**Verdict:** ${STATE_LABEL[run.verdict.state]}`);
  lines.push(`**When:** ${run.startedAt}`);
  lines.push(
    `**Node:** ${run.env.node} · **OS:** ${run.env.os} · **PM:** ${run.env.pm} · **CI:** ${run.env.ci}`,
  );
  lines.push("");
  lines.push("## Checks");
  lines.push("");
  lines.push("| Check | Status | Duration | Summary | Log |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const r of run.results) {
    const dur = r.durationMs ? `${(r.durationMs / 1000).toFixed(1)}s` : "—";
    const log = r.logRef ? cell(relative(root, r.logRef)) : "—";
    lines.push(
      `| ${r.checkId} | ${r.status} | ${dur} | ${cell(r.summary)} | ${log} |`,
    );
  }
  if (run.verdict.skipped.length) {
    lines.push("");
    lines.push("## Skipped");
    lines.push("");
    for (const reason of run.verdict.reasons) lines.push(`- ${reason}`);
  }
  const failures = run.results.filter((r) => r.outputTail);
  if (failures.length) {
    lines.push("");
    lines.push("## Failure output");
    for (const r of failures) {
      lines.push("");
      lines.push(`### ${r.checkId}`);
      lines.push("");
      lines.push("```");
      lines.push(r.outputTail ?? "");
      lines.push("```");
    }
  }
  lines.push("");
  lines.push(
    "_Generated by VerisKit. A `Partial` verdict means one or more capabilities did not run — it is not a pass._",
  );
  lines.push("");
  return lines.join("\n");
}
