import type { VerificationRun } from "../core/model.js";

const STATE_LABEL = {
  verified: "Verified",
  failed: "Failed",
  partial: "Partial",
} as const;

export function renderMarkdown(run: VerificationRun): string {
  const lines: string[] = [];
  lines.push("# Veris Verification Report");
  lines.push("");
  lines.push(`**Verdict:** ${STATE_LABEL[run.verdict.state]}`);
  lines.push(`**When:** ${run.startedAt}`);
  lines.push(
    `**Node:** ${run.env.node} · **OS:** ${run.env.os} · **PM:** ${run.env.pm} · **CI:** ${run.env.ci}`,
  );
  lines.push("");
  lines.push("## Checks");
  lines.push("");
  lines.push("| Check | Status | Duration | Summary |");
  lines.push("| --- | --- | --- | --- |");
  for (const r of run.results) {
    const dur = r.durationMs ? `${(r.durationMs / 1000).toFixed(1)}s` : "—";
    lines.push(`| ${r.checkId} | ${r.status} | ${dur} | ${r.summary} |`);
  }
  if (run.verdict.skipped.length) {
    lines.push("");
    lines.push("## Skipped");
    lines.push("");
    for (const reason of run.verdict.reasons) lines.push(`- ${reason}`);
  }
  lines.push("");
  lines.push(
    "_Generated by Veris. A `Partial` verdict means one or more capabilities did not run — it is not a pass._",
  );
  lines.push("");
  return lines.join("\n");
}
